import type { IntakeProfile, IntakeQuestion, TaskCategory } from './types.js';
export const U:IntakeQuestion[]=[
 {key:'access_restrictions',label:'Are there any access restrictions the provider should know about?',kind:'text',importance:'recommended'},
 {key:'special_constraints',label:'Is there anything else that could make this task harder or affect the price?',kind:'text',importance:'recommended'},
];
const q=(key:string,label:string,kind:IntakeQuestion['kind']='text',importance:IntakeQuestion['importance']='required',conditions?:IntakeQuestion['conditions'],options?:string[]):IntakeQuestion=>({key,label,kind,importance,conditions,options});
export const B:Record<TaskCategory,IntakeQuestion[]>={
 yard:[q('yard_work_type','What yard work is needed?','multiselect','required',undefined,['mowing','trimming','weeding','leaf_cleanup','branch_cleanup','planting','general_cleanup','other']),q('yard_size','About how large is the area that needs work?','select'),q('debris','Should the provider haul away the debris?','yesno'),q('debris_type','What kind of debris needs to be removed?','multiselect','required',[{key:'debris',operator:'equals',value:true}]),q('equipment_provided','Will you provide the required yard equipment?','yesno'),],
 cleaning:[q('property_type','What type of property is this?','select'),q('room_count','Approximately how many rooms need cleaning?','number'),q('cleaning_type','What kind of cleaning is needed?','select'),q('supplies_provided','Will cleaning supplies and equipment be provided?','yesno')],
 moving:[q('move_type','What kind of move is this?','select','required',undefined,['within_property','same_building','local_move','pickup_only','dropoff_only','loading_unloading','other']),q('item_count','Approximately how many items need to be moved?','number'),q('stairs','Are there stairs involved?','yesno'),q('stair_flights','How many flights of stairs are involved?','number','required',[{key:'stairs',operator:'equals',value:true}]),q('large_items','Are any items especially large or heavy?','yesno'),q('large_item_details','What large or heavy items are involved?','text','required',[{key:'large_items',operator:'equals',value:true}]),q('vehicle_required','Will the provider need to supply a vehicle?','yesno'),],
 assembly:[q('assembly_type','What are you assembling?'),q('assembly_count','How many items need to be assembled?','number'),q('assembly_state','What state are the items currently in?','select','recommended',undefined,['boxed_new','partially_assembled','disassembled','unknown']),q('instructions_available','Are the instructions or manual available?','yesno','recommended'),q('wall_mounting','Does anything need to be mounted to a wall?','yesno'),q('wall_type','What type of wall will the item be mounted to?','select','recommended',[{key:'wall_mounting',operator:'equals',value:true}]),],
 delivery:[q('delivery_item','What is being delivered?'),q('delivery_quantity','How many items or packages are being delivered?','number'),q('vehicle_size','What vehicle size does this need?','select','required'),q('heavy_or_fragile','Is anything especially heavy, fragile, or difficult to handle?','yesno'),q('pickup_access','What is pickup access like?','select','recommended',undefined,['curbside','ground_floor','stairs','elevator','loading_area','other']),q('dropoff_access','What is drop-off access like?','select','recommended',undefined,['curbside','ground_floor','stairs','elevator','loading_area','other']),q('loading_help','Will someone be available to help load or unload?','yesno','recommended'),],
 handyman:[q('handyman_job_type','What kind of handyman work is this?','select','required',undefined,['repair','installation','replacement','adjustment','mounting','maintenance','other']),q('work_type','What item or area needs work?'),q('work_count','How many items or separate areas need work?','number','recommended'),q('item_condition','What condition is the item or area currently in?','select','recommended',undefined,['working_but_needs_adjustment','partially_broken','not_working','damaged','new_installation','unknown']),q('materials_provided','Will the required materials or replacement parts be provided?','yesno'),q('special_tools','Does the job appear to require specialized tools?','yesno')],
 home_services:[q('service_type','What home service is needed?'),q('affected_area','What area of the property is affected?'),q('service_scale','How much of the property is affected?','select','required',undefined,['single_item','single_area','multiple_areas','whole_property','unknown']),q('currently_usable','Can the affected area or system still be used normally?','yesno','recommended'),q('existing_damage','Is there existing damage or anything the provider should inspect first?','yesno'),q('damage_details','Describe the existing damage or issue.','text','recommended',[{key:'existing_damage',operator:'equals',value:true}])],
 auto:[q('vehicle_details','What vehicle is this for?'),q('auto_service_type','What work does the vehicle need?'),q('vehicle_drivable','Is the vehicle currently drivable?','yesno'),q('parts_provided','Are the required parts already available?','yesno')],
 events:[q('event_type','What kind of event is this?'),q('guest_count','Approximately how many people will attend?','number'),q('event_help_type','What help do you need for the event?','multiselect'),q('event_duration','About how long will help be needed?','select','required',undefined,['under_2_hours','2_4_hours','4_8_hours','full_day','multiple_days','unknown']),q('venue_type','Where is the event taking place?','select','recommended',undefined,['home','event_venue','office','outdoor','other']),q('equipment_needed','Will the provider need to bring any event equipment or supplies?','yesno','recommended'),],
 pet_care:[q('pet_type','What type of pet needs care?'),q('pet_count','How many pets are involved?','number'),q('care_type','What type of care is needed?','multiselect'),q('care_duration','How long will care be needed?','select','required',undefined,['under_1_hour','few_hours','full_day','overnight','multiple_days']),q('care_frequency','How often is care needed?','select','recommended',undefined,['one_time','daily','multiple_times_per_day','recurring']),q('special_instructions','Are there any behavioral, feeding, medication, or handling instructions?','text','recommended'),],
 painting:[q('painting_surface','What surfaces need painting?','multiselect','required',undefined,['interior_walls','exterior_walls','ceiling','trim','doors','fence','deck','other']),q('painting_area','What room or area is being painted?'),q('painting_size','About how much surface needs painting?','select','required',undefined,['small_feature','one_room','several_rooms','whole_property','unknown']),q('surface_condition','What condition is the current surface in?','select','recommended',undefined,['good','minor_wear','peeling_or_cracked','damaged','unknown']),q('paint_provided','Will you provide the paint?','yesno','recommended'),q('prep_needed','Is preparation work such as sanding, scraping, patching, stripping, or priming needed?','yesno','recommended'),q('prep_details','What preparation work is needed?','multiselect','recommended',[{key:'prep_needed',operator:'equals',value:true}],['patching','sanding','scraping','stripping','priming','other']),q('existing_damage','Is there existing damage affecting the paint job?','yesno','recommended'),q('high_access','Are any areas high up or difficult to reach?','yesno','recommended'),q('color_change','How different is the new color from the existing color?','select','recommended',undefined,['similar','light_to_dark','dark_to_light','unknown']),q('coat_count','How many coats would you like?','number','optional')],
 plumbing:[q('plumbing_fixture','What fixture or plumbing component is involved?','select','required',undefined,['sink','toilet','shower','bathtub','faucet','pipe','water_heater','drain','other']),q('plumbing_issue','What plumbing issue or work is needed?','select','required',undefined,['leak','clog','low_pressure','no_water','installation','replacement','repair','other']),q('issue_scope','How much of the plumbing is affected?','select','recommended',undefined,['single_fixture','multiple_fixtures','whole_property','unknown']),q('active_leak','Is water currently leaking?','yesno','recommended'),q('water_shutoff_available','Can you access the relevant water shutoff?','yesno','recommended'),q('parts_provided','Do you have the required replacement parts?','yesno','recommended')],
 electrical:[q('electrical_fixture','What electrical fixture or component is involved?','select','required',undefined,['light','outlet','switch','ceiling_fan','breaker','panel','doorbell','other']),q('electrical_issue','What electrical issue or work is needed?','select','required',undefined,['not_working','installation','replacement','flickering','tripping','repair','other']),q('issue_scope','How much of the electrical system is affected?','select','recommended',undefined,['single_fixture','multiple_fixtures','room_or_area','whole_property','unknown']),q('power_available','Is power currently available to the relevant area or device?','yesno','recommended'),q('existing_wiring','Is existing wiring already present?','yesno','recommended'),q('parts_provided','Do you have the required fixture or replacement parts?','yesno','recommended'),q('panel_involved','Is the breaker or electrical panel explicitly involved?','yesno','recommended')],
 other:[q('task_goal','What result would you like the provider to achieve?'),q('task_duration_estimate','How long do you think this task could take?','select','required',undefined,['under_1_hour','1_3_hours','half_day','full_day','multiple_days','unknown']),q('work_location_type','Where will the work take place?','select','recommended',undefined,['indoors','outdoors','vehicle','business','multiple_locations','other']),q('heavy_or_awkward','Does the task involve anything heavy, bulky, fragile, or difficult to handle?','yesno','recommended'),q('materials_needed','Will the provider need to supply any materials or replacement items?','yesno','recommended'),q('provider_resources','What tools, equipment, or materials should the provider bring?','text','recommended')],
};
export const PROFILE_QUESTIONS:Record<IntakeProfile,IntakeQuestion[]>={
 cleaning_indoor:B.cleaning,
 cleaning_surface:[q('surface_type','What outdoor surface needs cleaning?','select','required',undefined,['driveway','patio','walkway','siding','concrete','deck','other']),q('surface_area','About how large is the surface?','text','recommended'),q('equipment_provided','Will you provide the required cleaning equipment?','yesno'),q('water_access','Is a usable water connection available near the work area?','yesno')],
 auto_repair:B.auto,
 auto_cleaning:[q('vehicle_details','What vehicle is this for?'),q('auto_cleaning_type','What kind of vehicle cleaning is needed?','select','required',undefined,['exterior_wash','interior_detail','full_detail','pressure_wash','other']),q('equipment_provided','Will you provide the required washing or detailing equipment?','yesno')],
};
export const PROFILE_CLARIFICATION_QUESTIONS:Record<'cleaning'|'auto',IntakeQuestion>={
 cleaning:q('intake_profile','What are you cleaning?','select','required',undefined,['cleaning_indoor','cleaning_surface','auto_cleaning']),
 auto:q('intake_profile','What kind of vehicle work do you need?','select','required',undefined,['auto_repair','auto_cleaning']),
};
function dedupeQuestions(questions:IntakeQuestion[]):IntakeQuestion[]{const seen=new Set<string>();return questions.filter((question)=>{if(seen.has(question.key))return false;seen.add(question.key);return true;});}
function primaryQuestions(category:TaskCategory,profile?:IntakeProfile|null):IntakeQuestion[]{if(category==='cleaning'||category==='auto'){if(profile)return PROFILE_QUESTIONS[profile]??[];if(profile===null)return [PROFILE_CLARIFICATION_QUESTIONS[category]];}return B[category];}
export function getQuestionsForIntake(primaryCategory:TaskCategory,secondaryIntents:readonly TaskCategory[]=[],profile?:IntakeProfile|null):IntakeQuestion[]{const secondary=secondaryIntents.filter((category,index,all)=>category!==primaryCategory&&category!=='other'&&all.indexOf(category)===index);return dedupeQuestions([...primaryQuestions(primaryCategory,profile),...secondary.flatMap((category)=>B[category]),...U]);}
export function getQuestionsForCategory(category:TaskCategory,profile?:IntakeProfile|null):IntakeQuestion[]{return getQuestionsForIntake(category,[],profile)}
export function getKnownIntakeQuestionKeys():Set<string>{return new Set([...Object.values(B).flat(),...Object.values(PROFILE_QUESTIONS).flat(),...Object.values(PROFILE_CLARIFICATION_QUESTIONS),...U].map((question)=>question.key));}
export const TASK_CATEGORIES=Object.freeze(['yard','cleaning','moving','assembly','delivery','handyman','home_services','auto','events','pet_care','painting','plumbing','electrical','other'] as const);


