export type ObjectFact = { object: string; quantity: number | null; evidence: string; confidence: number };
const NUMBER_WORDS: Record<string, number> = { one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,eleven:11,twelve:12,thirteen:13,fourteen:14,fifteen:15,sixteen:16,seventeen:17,eighteen:18,nineteen:19,twenty:20 };
const OBJECT_ALIASES: Array<{canonical:string; pattern:string}> = [
 {canonical:'washing machine',pattern:String.raw`washing machine(?:s)?`},{canonical:'refrigerator',pattern:String.raw`(?:refrigerator(?:s)?|fridge(?:s)?)`},{canonical:'couch',pattern:String.raw`(?:couch(?:es)?|sofa(?:s)?)`},{canonical:'mattress',pattern:String.raw`mattress(?:es)?`},{canonical:'dresser',pattern:String.raw`dresser(?:s)?`},{canonical:'piano',pattern:String.raw`piano(?:s)?`},{canonical:'cabinet',pattern:String.raw`cabinet(?:s)?`},{canonical:'wardrobe',pattern:String.raw`wardrobe(?:s)?`},{canonical:'lamp',pattern:String.raw`lamp(?:s)?`},{canonical:'stool',pattern:String.raw`stool(?:s)?`},{canonical:'shelf',pattern:String.raw`shel(?:f|ves)`},{canonical:'desk',pattern:String.raw`desk(?:s)?`},{canonical:'chair',pattern:String.raw`chair(?:s)?`},{canonical:'table',pattern:String.raw`table(?:s)?`},{canonical:'mirror',pattern:String.raw`mirror(?:s)?`},{canonical:'bed',pattern:String.raw`bed(?:s)?`},{canonical:'box',pattern:String.raw`box(?:es)?`},{canonical:'tv',pattern:String.raw`(?:tv(?:s)?|television(?:s)?)`},{canonical:'playset',pattern:String.raw`playset(?:s)?`},
];
function parseNumber(value:string|undefined):number|null { if(!value)return null; return /^\d+$/.test(value)?Number(value):NUMBER_WORDS[value.toLowerCase()]??null; }
function normalizeObjectPhrase(value:string):string { return value.toLowerCase().replace(/\b(?:new|old|large|small|huge|ikea|children['’]s|several|some)\b/gi,'').replace(/\bwithout breaking it\b.*$/i,'').replace(/\b(?:away|again after moving)\b.*$/i,'').replace(/\s+/g,' ').trim(); }
export function extractObjectFacts(input:string):ObjectFact[] { const text=input.toLowerCase(); const facts:ObjectFact[]=[]; const numberToken=String.raw`(?:\d+|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty)`; for(const alias of OBJECT_ALIASES){ const quantified=new RegExp(String.raw`\b(${numberToken})\s+(?:[\w'-]+\s+){0,2}?(${alias.pattern})\b`,'i'); const qm=text.match(quantified); if(qm){facts.push({object:alias.canonical,quantity:parseNumber(qm[1]),evidence:qm[0],confidence:.98});continue;} const singular=new RegExp(String.raw`\b${alias.pattern}\b`,'i'); const sm=text.match(singular); if(sm) facts.push({object:alias.canonical,quantity:null,evidence:sm[0],confidence:.94}); } return facts; }
export function totalObjectQuantity(facts:ObjectFact[]):number{return facts.reduce((t,f)=>t+(f.quantity??1),0);}
