import { extractIntakePrefill } from './extractPrefill.js';
import type { TaskCategory } from './types.js';

const cases = [
  ['Paint my living room walls.', 'painting', { painting_surface: 'interior_walls', painting_area: 'living room' }],
  ['Paint the bedroom ceiling.', 'painting', { painting_surface: 'ceiling', painting_area: 'bedroom' }],
  ['Paint my wooden fence.', 'painting', { painting_surface: 'fence' }],
  ['Repaint the front door.', 'painting', { painting_surface: 'doors' }],
  ['Paint the exterior walls of my house.', 'painting', { painting_surface: 'exterior_walls' }],
  ['Paint the deck.', 'painting', { painting_surface: 'deck' }],
  ['Paint the kitchen walls, I already have the paint.', 'painting', { painting_surface: 'interior_walls', painting_area: 'kitchen', paint_provided: true }],
  ['Paint two bedrooms, paint is not provided.', 'painting', { paint_provided: false }],
  ['Repaint the ceiling, there is some water damage.', 'painting', { painting_surface: 'ceiling', existing_damage: true }],
  ['Paint the trim around four windows.', 'painting', { painting_surface: 'trim' }],
  ['Kitchen sink is leaking.', 'plumbing', { plumbing_fixture: 'sink', plumbing_issue: 'leak', active_leak: true }],
  ['Toilet is clogged.', 'plumbing', { plumbing_fixture: 'toilet', plumbing_issue: 'clog' }],
  ['Install a new kitchen faucet.', 'plumbing', { plumbing_fixture: 'faucet', plumbing_issue: 'installation' }],
  ['Replace my bathroom sink.', 'plumbing', { plumbing_fixture: 'sink', plumbing_issue: 'replacement' }],
  ['Shower has very low water pressure.', 'plumbing', { plumbing_fixture: 'shower', plumbing_issue: 'low_pressure' }],
  ['Bathtub drain is clogged.', 'plumbing', { plumbing_fixture: 'drain', plumbing_issue: 'clog' }],
  ['Pipe under the sink is leaking.', 'plumbing', { plumbing_fixture: 'pipe', plumbing_issue: 'leak', active_leak: true }],
  ['Water heater needs repair.', 'plumbing', { plumbing_fixture: 'water_heater', plumbing_issue: 'repair' }],
  ['No water is coming from the kitchen faucet.', 'plumbing', { plumbing_fixture: 'faucet', plumbing_issue: 'no_water' }],
  ['Replace a leaking pipe, I already bought the replacement part.', 'plumbing', { plumbing_fixture: 'pipe', plumbing_issue: 'replacement', active_leak: true, parts_provided: true }],
  ['Replace a leaking faucet.', 'plumbing', { plumbing_fixture: 'faucet', plumbing_issue: 'replacement', active_leak: true }],
  ['Install a new faucet, no leak.', 'plumbing', { plumbing_fixture: 'faucet', plumbing_issue: 'installation', active_leak: false }],
  ['Sink is clogged and leaking.', 'plumbing', { plumbing_fixture: 'sink', plumbing_issue: 'clog', active_leak: true }],
  ['Replace toilet, no leak.', 'plumbing', { plumbing_fixture: 'toilet', plumbing_issue: 'replacement', active_leak: false }],
  ['Install two ceiling lights.', 'electrical', { electrical_fixture: 'light', electrical_issue: 'installation' }],
  ['Replace a broken outlet.', 'electrical', { electrical_fixture: 'outlet', electrical_issue: 'replacement' }],
  ['My bathroom light keeps flickering.', 'electrical', { electrical_fixture: 'light', electrical_issue: 'flickering' }],
  ['The breaker keeps tripping.', 'electrical', { electrical_fixture: 'breaker', electrical_issue: 'tripping' }],
  ['Install a new ceiling fan.', 'electrical', { electrical_fixture: 'ceiling_fan', electrical_issue: 'installation' }],
  ['Replace two light switches.', 'electrical', { electrical_fixture: 'switch', electrical_issue: 'replacement' }],
  ['Doorbell is not working.', 'electrical', { electrical_fixture: 'doorbell', electrical_issue: 'not_working' }],
  ['Install an outlet, wiring already exists.', 'electrical', { electrical_fixture: 'outlet', electrical_issue: 'installation', existing_wiring: true }],
  ['Replace a ceiling light, I already bought the fixture.', 'electrical', { electrical_fixture: 'light', electrical_issue: 'replacement', parts_provided: true }],
  ['The bedroom has no power.', 'electrical', { power_available: false }],
  ['Shower drain is blocked.', 'plumbing', { plumbing_fixture: 'drain', plumbing_issue: 'clog' }],
  ['Kitchen sink drain is clogged.', 'plumbing', { plumbing_fixture: 'drain', plumbing_issue: 'clog' }],
  ['Replace my bathtub.', 'plumbing', { plumbing_fixture: 'bathtub', plumbing_issue: 'replacement' }],
  ['Shower has low water pressure.', 'plumbing', { plumbing_fixture: 'shower', plumbing_issue: 'low_pressure' }],
  ['No preparation required.', 'painting', { prep_needed: false }],
  ['The walls are ready to paint.', 'painting', { prep_needed: false }],
  ['Sand the walls before painting.', 'painting', { prep_needed: true }],
  ['Patch and prime the wall first.', 'painting', { prep_needed: true }],
  ['Pipe under the sink is leaking.', 'plumbing', { plumbing_fixture: 'pipe', plumbing_issue: 'leak', active_leak: true }],
  ['Pipe behind the toilet is leaking.', 'plumbing', { plumbing_fixture: 'pipe' }],
  ['Drain under the sink is clogged.', 'plumbing', { plumbing_fixture: 'drain', plumbing_issue: 'clog' }],
  ['Kitchen sink is leaking.', 'plumbing', { plumbing_fixture: 'sink' }],
  ['Sink drain is clogged.', 'plumbing', { plumbing_fixture: 'drain' }],
  ['Replace the toilet.', 'plumbing', { plumbing_fixture: 'toilet', plumbing_issue: 'replacement' }],
  ['Paint is already here.', 'painting', { paint_provided: true }],
  ['The paint is here.', 'painting', { paint_provided: true }],
  ['I already have the paint.', 'painting', { paint_provided: true }],
  ['I bought the paint.', 'painting', { paint_provided: true }],
  ['Paint is not provided.', 'painting', { paint_provided: false }],
  ['I don\'t have paint.', 'painting', { paint_provided: false }],
  ['You need to bring the paint.', 'painting', { paint_provided: false }],
  ['Paint the room.', 'painting', {}],
  ['Install an outlet, wiring already exists.', 'electrical', { electrical_fixture: 'outlet', electrical_issue: 'installation', existing_wiring: true }],
  ['Install a ceiling light, existing wiring is there.', 'electrical', { electrical_fixture: 'light', electrical_issue: 'installation', existing_wiring: true }],
  ['This room is already wired.', 'electrical', { existing_wiring: true }],
  ['Install a fan, there is no wiring.', 'electrical', { existing_wiring: false }],
  ['New wiring is needed for the outlet.', 'electrical', { existing_wiring: false }],
  ['Install an outlet.', 'electrical', {}],
] as const;

const failures: string[] = [];
for (const [input, category, expected] of cases) {
  const actual = extractIntakePrefill(input, category as TaskCategory).answers;
  for (const [key, value] of Object.entries(expected)) if (actual[key] !== value) failures.push(`Input: "${input}"\nField: ${key}\nExpected: ${JSON.stringify(value)}\nActual: ${JSON.stringify(actual[key])}`);
}
if (failures.length) { console.error(`Expanded category prefill failures: ${failures.length}`); failures.forEach((failure, index) => console.error(`\n${index + 1}. ${failure}`)); process.exitCode = 1; } else console.log(`Expanded category prefill cases passed: ${cases.length}`);
