import type { ServiceTaskCategory } from './types.js';

export interface ClassifierDevelopmentCase {
  group: string;
  input: string;
  expectedCategory: ServiceTaskCategory | null;
}

const makeCases = (
  group: string,
  expectedCategory: ServiceTaskCategory | null,
  inputs: readonly string[]
): ClassifierDevelopmentCase[] => inputs.map((input) => ({ group, input, expectedCategory }));

const moving = [
  'Carry the wardrobe into the upstairs bedroom.',
  'Shift the sofa from the den to the living room.',
  'Move eight cartons down to the basement.',
  'Relocate the dining set to the other side of the house.',
  'Help lift the mattress up one flight.',
  'Take the bookcase into the spare room.',
  'Move our furniture out of the nursery.',
  'Carry two end tables down the stairs.',
  'Rearrange the couch and chairs in the lounge.',
  'Load the apartment furniture into our rented moving truck.',
  'Unload my belongings into the new flat.',
  'Move the piano from the hall into the study.',
  'Carry a heavy dresser across the apartment.',
  'Shift ten moving boxes into the garage.',
  'Take the bed frame upstairs to the main bedroom.',
  'Move the refrigerator from the kitchen to the utility room.',
  'Carry several stools to the lower level.',
  'Relocate my desk and filing cabinet within the office.',
  'Help move everything out of one bedroom.',
  'Lift the couch through the narrow hallway.',
  'Bring the furniture down from the third floor to our truck.',
  'Move a bulky armoire into the next room.',
  'Carry the television stand to the basement.',
  'Shift the washer and dryer across the laundry room.',
  'Move my household belongings into the storage unit.',
] as const;

const delivery = [
  'Collect the mirror from the seller and deliver it to my address.',
  'Pick up a parcel at the depot and drop it at my office.',
  'Transport the dining table from the shop to my apartment.',
  'Bring the birthday cake from the bakery to the venue.',
  'Deliver these documents to the client downtown.',
  'Collect a television from the store and bring it home.',
  'Take the donated clothes to the community center.',
  'Pick up the appliance from the warehouse and deliver it here.',
  'Courier a package from my house to another address.',
  'Bring the purchased desk from the showroom to my workplace.',
  'Collect the flowers and deliver them to the reception hall.',
  'Take this sealed box to the shipping center.',
  'Fetch a lamp from the seller and bring it to my flat.',
  'Deliver thirty folding chairs to the conference venue.',
  'Pick up groceries and drop them at my parents’ house.',
  'Transport a framed painting to the gallery across town.',
  'Bring the replacement refrigerator from the retailer to my home.',
  'Collect the order at the hardware store and deliver it to the job site.',
  'Take the luggage from the hotel to the airport terminal.',
  'Pick up a sofa from the marketplace seller and bring it here.',
  'Deliver the medical supplies to the clinic address.',
  'Fetch the keys from the landlord and bring them to me.',
  'Transport the computer equipment between our two offices.',
  'Collect a small cabinet at the auction house and deliver it home.',
  'Drop off this envelope at the solicitor’s office.',
] as const;

const handymanRepair = [
  'Tighten the loose cupboard handle.',
  'Repair the sticking bedroom door.',
  'Patch a small hole in the plasterboard.',
  'Fix the sagging garden gate.',
  'Replace the broken cabinet hinge.',
  'Secure the wobbly stair rail.',
  'Mend the cracked closet door.',
  'Adjust the shelf bracket that came loose.',
  'Repair a damaged section of skirting board.',
  'Fix the latch on the backyard fence.',
  'Tighten the screws on the handrail.',
  'Patch a dent in the interior wall.',
  'Repair the jammed sliding closet.',
  'Replace the towel-bar bracket.',
  'Fix a loose doorstop.',
  'Reattach the detached cupboard trim.',
  'Repair the wooden window latch.',
  'Tighten the hardware on the pantry door.',
  'Fix the damaged baseboard corner.',
  'Mend the loose gate post hardware.',
  'Repair a cracked drawer front.',
  'Adjust the interior door so it closes.',
  'Secure the loose banister bracket.',
  'Fix the broken wardrobe handle.',
  'Patch the screw holes left in the wall.',
] as const;

const assemblyWork = [
  'Assemble the flat-pack wardrobe.',
  'Put together six dining chairs.',
  'Build the new computer desk from its parts.',
  'Mount three floating shelves on drywall.',
  'Assemble the children’s bunk bed.',
  'Put the barbecue grill together.',
  'Build the bookcase and anchor it to the wall.',
  'Assemble two bedside cabinets.',
  'Mount the television bracket on brick.',
  'Put together the outdoor playset.',
  'Build four office desks from boxes.',
  'Assemble the modular storage rack.',
  'Attach the new mirror to the wall.',
  'Put the shoe cabinet together.',
  'Assemble a dining table and four stools.',
  'Wall-mount the coat rack.',
  'Build the trampoline from the supplied pieces.',
  'Assemble the flat-pack dresser.',
  'Mount a pair of display shelves on concrete.',
  'Put together the patio furniture set.',
  'Build the new bed frame.',
  'Assemble the standing workstation.',
  'Mount the bathroom cabinet to the wall.',
  'Put together the media console.',
  'Assemble and secure the tall bookshelf.',
] as const;

const plumbingWork = [
  'Unclog the shower drain.',
  'The kitchen tap is dripping continuously.',
  'Replace the cracked supply pipe.',
  'Install a new bathroom sink.',
  'The toilet will not stop running.',
  'Repair the hot-water heater.',
  'There is no water at the upstairs faucet.',
  'Water backs up through the bath drain.',
  'Fix the leak beneath the washbasin.',
  'Water pressure is weak in the shower.',
  'Replace the old toilet.',
  'Install a mixer tap in the kitchen.',
  'The pipe behind the toilet is leaking.',
  'Clear a clogged kitchen drain.',
  'Repair the broken water line.',
  'The faucet keeps dripping after it is closed.',
  'Fit a replacement water heater.',
  'No water comes through the bathroom tap.',
  'The shower has almost no pressure.',
  'Replace a leaking drain pipe.',
  'Install the customer-provided toilet.',
  'Fix the blocked sink outlet.',
  'A plumbing pipe burst in the utility room.',
  'Repair the leaking bathtub fitting.',
  'Change the worn faucet cartridge.',
] as const;

const electricalWork = [
  'Replace the dead wall socket.',
  'Install two ceiling lamps.',
  'The breaker trips whenever the kettle runs.',
  'Fit a new ceiling fan.',
  'The hallway light keeps flickering.',
  'Install another outlet beside the desk.',
  'Replace the faulty light switch.',
  'The doorbell has stopped working.',
  'The main fuse board needs electrical repair.',
  'There is no power in the bedroom.',
  'Wire and install a bathroom fan.',
  'Change a broken receptacle.',
  'Install the customer’s pendant light.',
  'The circuit breaker keeps cutting out.',
  'Replace the old doorbell transformer.',
  'Add a light fixture in the corridor.',
  'The kitchen socket is completely dead.',
  'Repair wiring at the ceiling fan.',
  'Install three dimmer switches.',
  'Replace a breaker inside the panel.',
  'The porch light flashes on and off.',
  'Put in a new power outlet.',
  'The fan works but needs rewiring.',
  'Replace two damaged switches.',
  'An electrician is needed for the breaker panel.',
] as const;

const electricalAdjacentHandyman = [
  'Patch the plaster beside the outlet.',
  'Repair the cabinet under the light switch.',
  'Tighten the shelf bracket below the wall lamp.',
  'Fix the cupboard door near the breaker box.',
  'Mend the trim around the ceiling-light opening.',
  'Repair a loose desk beside the power socket.',
  'Patch the wall after an outlet was removed.',
  'Fix the closet latch next to the switch.',
  'Reattach the wooden cover around the doorbell.',
  'Repair the shelf that holds the table lamp.',
  'Tighten the cabinet hinge beneath the light.',
  'Patch a small hole beside the electrical panel.',
  'Fix the sticking door near the fuse box.',
  'Repair chipped trim around a wall switch.',
  'Secure the bookcase next to the outlet.',
  'Mend the drywall behind the ceiling-fan control.',
  'Tighten the handrail beside the hallway light.',
  'Repair a cracked drawer below the socket.',
  'Fix the fence latch near the outdoor light.',
  'Patch the ceiling after the lamp was moved.',
  'Secure a mirror beside the light switch.',
  'Repair the wooden panel around the outlet.',
  'Fix a loose cabinet near the breaker panel.',
  'Reattach the baseboard below the power point.',
  'Mend the closet track beside the wall light.',
] as const;

const nonSpecialistHandyman = [
  'Repair the loose cupboard hinge.',
  'Fix a cracked garden gate.',
  'Patch the drywall beside the sink.',
  'Tighten the cabinet handle in the bathroom.',
  'Repair the shelf above the toilet.',
  'Fix the wooden trim near the shower.',
  'Replace a damaged closet latch.',
  'Secure the loose rail by the kitchen.',
  'Patch a wall hole behind the faucet.',
  'Repair the pantry door.',
  'Fix the fence panel near the outside tap.',
  'Tighten the bracket below the bathroom shelf.',
  'Repair the wooden vanity drawer.',
  'Fix the bedroom door handle.',
  'Patch the plaster around the pipe opening.',
  'Replace the cabinet-door hinge.',
  'Secure the loose towel rack.',
  'Repair a chipped wooden handrail.',
  'Fix the gate latch beside the water meter.',
  'Patch the access hole in the wall.',
  'Tighten the loose desk hardware.',
  'Repair the wardrobe track.',
  'Fix the sticking cupboard door.',
  'Replace the broken shelf support.',
  'Mend the cracked baseboard.',
] as const;

const eventCases = [
  'Set up tables for a retirement reception with sixty guests.',
  'Help serve a graduation banquet for eighty attendees.',
  'Decorate the hall for an engagement party.',
  'Host a company dinner for one hundred people.',
  'Clean up the venue after the wedding reception.',
  'Arrange chairs for a baby shower with thirty guests.',
  'Manage the buffet at our annual corporate event.',
  'Bartend at a private birthday celebration.',
  'Tear down decorations after the awards ceremony.',
  'Check in guests at the charity gala.',
  'Prepare the room for an anniversary dinner for forty people.',
  'Provide setup help for a graduation gathering.',
  'Serve drinks at the office party.',
  'Set up tents for the outdoor wedding.',
  'Help coordinate a reception for seventy attendees.',
] as const;

const gatheringVague = [
  'Make supper for my family.',
  'Need help for two hours this evening.',
  'Can somebody come over tomorrow?',
  'Looking for a reliable service person.',
  'I have people coming by later.',
  'Need an extra pair of hands today.',
  'Someone should help around the house.',
  'Can a worker be here in the morning?',
  'Looking for assistance next weekend.',
  'I need a person for a short job.',
  'Help me prepare dinner at home.',
  'There will be a few people here.',
  'Can someone handle something quickly?',
  'Need general assistance before Friday.',
  'Looking for somebody experienced.',
] as const;

const petCare = [
  'Walk the two dogs before lunch.',
  'Feed my cat while I am away.',
  'Pet-sit three kittens overnight.',
  'Give the elderly dog its medication.',
  'Check on the parrot and refill its water.',
  'Take my puppy for an afternoon walk.',
  'Watch the cats for the weekend.',
  'Feed and exercise four dogs.',
  'Stay with my nervous cat for an hour.',
  'Look after the fish during my trip.',
  'Visit twice daily to feed the pets.',
  'Walk one dog and sit with the other.',
  'Care for a puppy that needs medicine.',
  'Check on two cats and clean their bowls.',
  'Pet-sit my dog until I return.',
] as const;

const petRelatedCleaning = [
  'Remove dog hair from the living-room carpet.',
  'Clean cat litter scattered across the floor.',
  'Scrub the pet stain from the sofa.',
  'Vacuum fur from all the furniture.',
  'Clean the room after a puppy accident.',
  'Remove the animal odor from the rug.',
  'Wash muddy paw marks from the hallway.',
  'Deep-clean the carpet where the dog was sick.',
  'Scrub the litter area in the utility room.',
  'Clean pet hair out of the car upholstery.',
] as const;

const petHomeServices = [
  'Inspect the roof leak above the outdoor kennel.',
  'Inspect damage around the pet flap.',
  'Fix the ventilation issue in the kennel room.',
  'Check water damage beneath the aquarium stand.',
  'Service the broken exhaust vent in the pet room.',
] as const;

const homeServices = [
  'Inspect damaged flashing around the roof vent.',
  'Service the garage-door opening mechanism.',
  'Check the chimney cap for storm damage.',
  'Inspect the attic ventilation problem.',
  'Repair the mechanism inside the window frame.',
  'Investigate moisture appearing beneath the bathroom floor.',
  'Check why the dishwasher will not drain.',
  'Service the garbage disposal unit.',
  'Inspect mold-like marks around the window.',
  'Check the air conditioner that is not cooling.',
  'Inspect a damaged section of wooden flooring.',
  'Service the bathroom exhaust vent.',
  'Investigate water beneath the washing machine.',
  'Inspect the crack spreading across the wall.',
  'Repair the automatic garage-door opener.',
] as const;

const homeHandyman = [
  'Fix the loose interior door handle.',
  'Patch a small crack in drywall.',
  'Repair the wooden fence latch.',
  'Tighten a wobbly banister.',
  'Replace the cupboard hinge.',
  'Adjust the closet door track.',
  'Secure a shelf bracket to the wall.',
  'Repair chipped baseboard trim.',
  'Fix the sticking pantry door.',
  'Patch holes left by old pictures.',
  'Mend a loose garden gate.',
  'Replace the broken towel rail.',
  'Tighten the wardrobe handle.',
  'Fix the sagging cabinet door.',
  'Repair a loose stair railing.',
] as const;

const shortClear: Array<readonly [string, ServiceTaskCategory]> = [
  ['Mow the lawn.', 'yard'],
  ['Trim the hedges.', 'yard'],
  ['Deep-clean the apartment.', 'cleaning'],
  ['Vacuum the office.', 'cleaning'],
  ['Move the sofa upstairs.', 'moving'],
  ['Unload the moving truck.', 'moving'],
  ['Assemble the desk.', 'assembly'],
  ['Mount the TV bracket.', 'assembly'],
  ['Deliver this parcel.', 'delivery'],
  ['Collect my order.', 'delivery'],
  ['Fix the cupboard hinge.', 'handyman'],
  ['Patch the drywall.', 'handyman'],
  ['Inspect the roof vent.', 'home_services'],
  ['Service the garage door.', 'home_services'],
  ['Replace my brake pads.', 'auto'],
  ['Change the car battery.', 'auto'],
  ['Set up the wedding.', 'events'],
  ['Decorate for the party.', 'events'],
  ['Walk my dog.', 'pet_care'],
  ['Feed the cats.', 'pet_care'],
  ['Paint the bedroom.', 'painting'],
  ['Repaint the fence.', 'painting'],
  ['Unclog the toilet.', 'plumbing'],
  ['Replace the faucet.', 'plumbing'],
  ['Install an outlet.', 'electrical'],
  ['Fix the breaker.', 'electrical'],
  ['Clean the windows.', 'cleaning'],
  ['Move the wardrobe.', 'moving'],
  ['Repair the handrail.', 'handyman'],
  ['Paint the ceiling.', 'painting'],
] as const;

const multiIntent: Array<readonly [string, ServiceTaskCategory]> = [
  ['Move the dresser upstairs and assemble the new bed.', 'moving'],
  ['Clean the kitchen and fix the leaking faucet.', 'plumbing'],
  ['Paint the bedroom after patching the wall.', 'painting'],
  ['Pick up the desk, deliver it home, and assemble it.', 'delivery'],
  ['Move the couch and mount the television afterward.', 'moving'],
  ['Install the new sink and repair the cupboard hinge.', 'plumbing'],
  ['Replace the outlet and patch the surrounding drywall.', 'electrical'],
  ['Clean the carpet and remove the pet hair.', 'cleaning'],
  ['Set up party tables and clean the venue afterward.', 'events'],
  ['Paint the fence after tightening its loose latch.', 'painting'],
  ['Carry the boxes downstairs and load our moving van.', 'moving'],
  ['Deliver the wardrobe and assemble it at the destination.', 'delivery'],
  ['Repair the leaking shower and repaint the damaged wall.', 'plumbing'],
  ['Mount shelves and fix the old bracket.', 'assembly'],
  ['Walk the dog and clean its feeding area.', 'pet_care'],
  ['Inspect the roof and clear branches from the gutter.', 'home_services'],
  ['Replace the ceiling fan and patch the old screw holes.', 'electrical'],
  ['Clean the garage and move the stored furniture aside.', 'cleaning'],
  ['Move the dining table, then put the chairs together.', 'moving'],
  ['Pick up the mirror and mount it after delivery.', 'delivery'],
  ['Paint the deck and replace a loose board.', 'painting'],
  ['Install the faucet and tighten the cabinet door.', 'plumbing'],
  ['Assemble the cabinet and secure it to the wall.', 'assembly'],
  ['Service the garage door and replace its loose handle.', 'home_services'],
  ['Replace the car battery and clean the terminals.', 'auto'],
  ['Feed the cats and vacuum the litter area.', 'pet_care'],
  ['Mow the lawn and haul the garden waste away.', 'yard'],
  ['Decorate the reception and serve the guests.', 'events'],
  ['Install a light and repaint the ceiling around it.', 'electrical'],
  ['Repair the gate and clear the cut branches.', 'handyman'],
] as const;

const vague = [
  'Need help soon.',
  'Can somebody stop by?',
  'Looking for a worker.',
  'I have a small job.',
  'Need assistance tomorrow.',
  'Someone experienced required.',
  'Can you handle something for me?',
  'Looking for general help.',
  'Need a person this afternoon.',
  'There is work to be done.',
  'Can someone come to my place?',
  'A quick task needs doing.',
  'Need somebody for the morning.',
  'I could use an extra hand.',
  'Looking for local assistance.',
  'Please send someone reliable.',
  'Need help for an hour.',
  'Can a worker visit next week?',
  'There is an issue at home.',
  'I need something taken care of.',
  'Looking for help this weekend.',
  'Can someone check this?',
  'Need a service person nearby.',
  'A household task needs attention.',
  'Could somebody assist me?',
  'Need help at the property.',
  'Looking for a capable person.',
  'Can somebody help later?',
  'I have a job with few details.',
  'Need someone available today.',
] as const;

export const classifierDevelopmentCases: ClassifierDevelopmentCase[] = [
  ...makeCases('moving_vs_delivery', 'moving', moving),
  ...makeCases('moving_vs_delivery', 'delivery', delivery),
  ...makeCases('handyman_vs_assembly', 'handyman', handymanRepair),
  ...makeCases('handyman_vs_assembly', 'assembly', assemblyWork),
  ...makeCases('handyman_vs_plumbing', 'plumbing', plumbingWork),
  ...makeCases('handyman_vs_plumbing', 'handyman', nonSpecialistHandyman),
  ...makeCases('handyman_vs_electrical', 'electrical', electricalWork),
  ...makeCases('handyman_vs_electrical', 'handyman', electricalAdjacentHandyman),
  ...makeCases('events_vs_vague', 'events', eventCases),
  ...makeCases('events_vs_vague', null, gatheringVague),
  ...makeCases('pet_vs_cleaning_home', 'pet_care', petCare),
  ...makeCases('pet_vs_cleaning_home', 'cleaning', petRelatedCleaning),
  ...makeCases('pet_vs_cleaning_home', 'home_services', petHomeServices),
  ...makeCases('home_services_vs_handyman', 'home_services', homeServices),
  ...makeCases('home_services_vs_handyman', 'handyman', homeHandyman),
  ...shortClear.map(([input, expectedCategory]) => ({
    group: 'short_clear',
    input,
    expectedCategory,
  })),
  ...multiIntent.map(([input, expectedCategory]) => ({
    group: 'multi_intent',
    input,
    expectedCategory,
  })),
  ...makeCases('vague_abstention', null, vague),
];
