import type { RawTaskClassification, ServiceTaskCategory } from './types.js';
export interface ClassificationOverride { category: ServiceTaskCategory; secondaryIntents: ServiceTaskCategory[]; reason: string; }
function normalize(value: string): string { return value.toLowerCase().replace(/\s+/g, ' ').trim(); }
export function findClassificationOverride(raw: string, _classification: RawTaskClassification): ClassificationOverride | null {
  const text = normalize(raw);
  if (/\b(?:paint|painting|repaint|painter|painted)\b/.test(text) && /\b(?:wall|walls|ceiling|trim|baseboard|door|fence|deck|house|room)\b/.test(text)) return { category: 'painting', secondaryIntents: [], reason: 'explicit_painting_request' };
  if (/\b(?:sink|toilet|shower|bathtub|tub|faucet|tap|pipe|piping|water heater|drain|plumber|plumbing)\b/.test(text) && /\b(?:leak|leaking|clog|clogged|blocked|pressure|water|install|replace|repair|fix|drip)\b/.test(text)) return { category: 'plumbing', secondaryIntents: [], reason: 'explicit_plumbing_request' };
  if (/\b(?:move|carry|relocate|take)\b/.test(text) && /\b(?:wardrobe|dresser|couch|sofa|table|chair|chairs|desk|bed|mattress|bookcase|bookshelf|lamp|piano|furniture|stool|stools)\b/.test(text) && !/\b(?:package|parcel|shipment|delivery|address)\b/.test(text)) return { category: 'moving', secondaryIntents: [], reason: 'explicit_household_moving_request' };
  if (/\b(?:mount|wall[ -]?mount|install)\b[^.!?]{0,40}\b(?:shelves?|tv|television|mirrors?|cabinets?)\b/.test(text) && !/\b(?:electrical|wiring|outlet|switch|breaker|light|ceiling fan)\b/.test(text)) return { category: 'assembly', secondaryIntents: [], reason: 'explicit_wall_mounting_request' };
  if (/\bbring\b/.test(text) && !/\bbring\s+(?:your own\s+)?(?:an?\s+)?(?:truck|van|car|suv|drill|ladder|mower|rake|leaf blower|tools?|materials?|supplies?|paint|replacement parts?|equipment)\b/.test(text) && /\b(?:tv|television|lamp|lamps|vase|desk|table|cabinet|sofa|couch|shelf|shelves|box|boxes|package|refrigerator|bed|piano)\b/.test(text)) return { category: 'delivery', secondaryIntents: [], reason: 'explicit_bring_task_object' };
  if (/\brake\b/.test(text) && /\b(?:blower|leaf blower)\b/.test(text) && /\b(?:cleanup|clean[- ]up|leaves?|branches?|yard|lawn|outdoor)\b/.test(text)) return { category: 'yard', secondaryIntents: [], reason: 'explicit_yard_tool_cleanup' };
  if (/\b(?:fix|repair|tighten|replace)\b[^.!?]{0,40}\b(?:fence|handrail|hinge|screen door)\b/.test(text) && !/\b(?:electrical|wiring|outlet|switch|breaker|light|ceiling fan)\b/.test(text)) return { category: 'handyman', secondaryIntents: [], reason: 'explicit_handyman_repair' };
  if (/\b(?:roof|chimney|(?:bathroom|attic)\s+exhaust vent|attic vent|window mechanism|garage door|patio screen door)\b/.test(text) && /\b(?:inspect|check|service|repair|replace|issue|damaged|broken|damage)\b/.test(text)) return { category: 'home_services', secondaryIntents: [], reason: 'explicit_home_services_domain' };
  if (/\b(?:transmission|wiper blades?|windshield wipers?)\b/.test(text) && /\b(?:car|vehicle|sedan|truck|auto|inspect|replace|repair)\b/.test(text)) return { category: 'auto', secondaryIntents: [], reason: 'explicit_automotive_context' };
  if (/\b(?:clean|clean up|wash|scrub|vacuum|mop)\b/.test(text) && /\b(?:office|workspace|room|house|apartment|floor|bathroom|kitchen|window|carpet|garage)\b/.test(text) && !/\b(?:party|wedding|event|guests?)\b/.test(text)) return { category: 'cleaning', secondaryIntents: [], reason: 'explicit_cleaning_request' };
  const electricalFixture = /\b(?:electrical|light|lights|outlet|socket|receptacle|switch|ceiling fan|breaker|doorbell|electrician)\b/.test(text) || /\b(?:electrical|breaker)\s+panel\b/.test(text);
  if (electricalFixture && /\b(?:install|replace|repair|fix|working|flicker|flickering|trip|tripping|power|wiring|broken|dead)\b/.test(text)) return { category: 'electrical', secondaryIntents: [], reason: 'explicit_electrical_request' };
  if (/\b(pet|dog|cat)\b/.test(text) && /\b(hair|waste|litter|stain|odor|mess)\b/.test(text) && /\b(clean|remove|vacuum|scrub)\b/.test(text)) return { category: 'cleaning', secondaryIntents: [], reason: 'pet_related_cleaning' };
  if (/\b(assemble|assembly|put\b(?:\s+\w+){0,3}\s+together|build)\b/.test(text) && !/\b(pick\s*up|pickup|deliver|delivery|transport|bring\s+(?:it|them|this|that)\s+(?:home|over|to))\b/.test(text)) return { category: 'assembly', secondaryIntents: [], reason: 'explicit_assembly_action' };
  if (/\b(pick\s*up|pickup|collect|deliver|transport)\b/.test(text) && /\b(bring|deliver|transport|to|home|house|property|venue|center)\b/.test(text)) { const secondary: ServiceTaskCategory[] = []; if (/\b(assemble|put\b(?:\s+\w+){0,3}\s+together)\b/.test(text)) secondary.push('assembly'); if (/\b(install|mount|attach)\b/.test(text)) secondary.push('handyman'); return { category: 'delivery', secondaryIntents: secondary, reason: 'explicit_pickup_delivery' }; }
  if (/\b(party|wedding|reception|event|baby shower|corporate event)\b/.test(text) && /\b(set\s*up|setup|tear\s*down|cleanup|clean\s*up|serve|decorate|bartend|buffet|guests)\b/.test(text)) return { category: 'events', secondaryIntents: [], reason: 'explicit_event_context' };
  if (/\b(dog|dogs|cat|cats|puppy|pet|pets|fish|parrot)\b/.test(text) && /\b(walk|feed|watch|sit|look after|check on|medication|vet)\b/.test(text)) return { category: 'pet_care', secondaryIntents: [], reason: 'explicit_pet_care_action' };
  return null;
}
