ALTER TABLE public.business_assessment_requests ADD COLUMN IF NOT EXISTS assessment_fee_cents INTEGER NULL;
ALTER TABLE public.business_assessment_requests ADD COLUMN IF NOT EXISTS assessment_platform_fee_cents INTEGER NULL;
ALTER TABLE public.business_assessment_requests ADD CONSTRAINT business_assessment_requests_fee_positive_ck CHECK (assessment_fee_cents IS NULL OR assessment_fee_cents > 0);
ALTER TABLE public.business_assessment_requests ADD CONSTRAINT business_assessment_requests_platform_fee_ck CHECK (assessment_platform_fee_cents IS NULL OR (assessment_platform_fee_cents >= 0 AND assessment_fee_cents IS NOT NULL AND assessment_platform_fee_cents <= assessment_fee_cents));
CREATE TABLE IF NOT EXISTS public.assessment_payments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), assessment_request_id UUID NOT NULL REFERENCES business_assessment_requests(id) ON DELETE RESTRICT, task_draft_id UUID NOT NULL REFERENCES task_drafts(id) ON DELETE RESTRICT, business_organization_id UUID NOT NULL REFERENCES business_organizations(id) ON DELETE RESTRICT, poster_user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, provider TEXT NOT NULL, provider_payment_id TEXT NOT NULL, provider_merchant_id TEXT NOT NULL, amount_cents INTEGER NOT NULL CHECK(amount_cents>0), platform_fee_cents INTEGER NOT NULL CHECK(platform_fee_cents>=0 AND platform_fee_cents<=amount_cents), status TEXT NOT NULL CHECK(status IN ('PENDING','SUCCEEDED','FAILED','REFUNDED')), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(provider,provider_payment_id), UNIQUE(assessment_request_id));
CREATE INDEX IF NOT EXISTS assessment_payments_draft_idx ON assessment_payments(task_draft_id);
CREATE INDEX IF NOT EXISTS assessment_payments_business_idx ON assessment_payments(business_organization_id);
ALTER TABLE public.business_assessment_requests DROP CONSTRAINT IF EXISTS business_assessment_requests_status_check;
ALTER TABLE public.business_assessment_requests ADD CONSTRAINT business_assessment_requests_status_check CHECK(status IN ('PENDING_ADMIN','ADMIN_REJECTED','AWAITING_CUSTOMER','SCHEDULED','COMPLETED','CANCELLED','CUSTOMER_DECLINED'));
