export type WorkspaceErrorCode = 'BAD_REQUEST' | 'FORBIDDEN' | 'CONFLICT'
  | 'PRECONDITION_FAILED' | 'INTERNAL_SERVER_ERROR';

const ERROR_CODES: Readonly<Record<string, WorkspaceErrorCode>> = {
  BUSINESS_PERMISSION_DENIED: 'FORBIDDEN', BUSINESS_SELF_APPROVAL_DENIED: 'FORBIDDEN',
  IDEMPOTENCY_CONFLICT: 'CONFLICT', BUSINESS_OWNER_REQUIRED: 'PRECONDITION_FAILED',
  BUSINESS_CLIENT_MODE_REQUIRED: 'PRECONDITION_FAILED',
  BUSINESS_APPROVAL_NOT_PENDING: 'PRECONDITION_FAILED',
  BUSINESS_SPEND_NOT_APPROVED: 'PRECONDITION_FAILED',
  BUSINESS_BIND_BUDGET_EXCEEDED: 'PRECONDITION_FAILED',
  BUSINESS_WORK_ORDER_COMPLIANCE_BLOCKED: 'PRECONDITION_FAILED',
  BUSINESS_RECURRING_COMPLIANCE_BLOCKED: 'PRECONDITION_FAILED',
  BUSINESS_RECURRING_POLICY_REQUIRED: 'PRECONDITION_FAILED',
  BUSINESS_RECURRING_TASK_CAP_EXCEEDED: 'PRECONDITION_FAILED',
  BUSINESS_RECURRING_PO_REQUIRED: 'PRECONDITION_FAILED',
  BUSINESS_RECURRING_COST_CENTER_REQUIRED: 'PRECONDITION_FAILED',
};

export function workspaceErrorCode(code: string): WorkspaceErrorCode {
  return ERROR_CODES[code]
    ?? (code.endsWith('_FAILED') ? 'INTERNAL_SERVER_ERROR' : 'BAD_REQUEST');
}
