export type ServiceBusinessRouterCode = 'BAD_REQUEST' | 'FORBIDDEN' | 'CONFLICT'
  | 'PRECONDITION_FAILED' | 'INTERNAL_SERVER_ERROR';

const ERROR_CODES: Readonly<Record<string, ServiceBusinessRouterCode>> = {
  BUSINESS_PERMISSION_DENIED: 'FORBIDDEN',
  BUSINESS_PAYOUT_ADMIN_REQUIRED: 'FORBIDDEN',
  IDEMPOTENCY_CONFLICT: 'CONFLICT',
  ASSIGNMENT_CONFLICT: 'CONFLICT',
  OPPORTUNITY_NOT_AVAILABLE: 'PRECONDITION_FAILED',
  OFFER_NOT_CURRENT: 'PRECONDITION_FAILED',
  OFFER_NOT_READY: 'PRECONDITION_FAILED',
  TASK_NOT_FUNDED: 'PRECONDITION_FAILED',
  QUOTE_NOT_READY: 'PRECONDITION_FAILED',
  QUOTE_OUT_OF_BOUNDS: 'PRECONDITION_FAILED',
  BUSINESS_PROVIDER_VERIFICATION_REQUIRED: 'PRECONDITION_FAILED',
  BUSINESS_PAYOUT_NOT_READY: 'PRECONDITION_FAILED',
  SERVICE_BUSINESS_INELIGIBLE: 'PRECONDITION_FAILED',
  SERVICE_BUSINESS_BINDING_INVALID: 'PRECONDITION_FAILED',
  SERVICE_BUSINESS_RESPONSE_INVALID: 'PRECONDITION_FAILED',
};

export function serviceBusinessRouterCode(code: string): ServiceBusinessRouterCode {
  return ERROR_CODES[code]
    ?? (code.endsWith('_FAILED') ? 'INTERNAL_SERVER_ERROR' : 'BAD_REQUEST');
}
