import type { ServiceResult } from '../../types.js';
import { chargeStaxPaymentMethod, getStaxTransaction } from './StaxClient.js';
import { StaxMerchantAccountService } from './StaxMerchantAccountService.js';
export interface CreateStaxQuotePaymentInput { quoteId:string; quoteVersionId:string; posterId:string; businessOrganizationId:string; paymentMethodId:string; amountCents:number; platformFeeCents:number; }
export interface CreateStaxQuotePaymentResult { transactionId:string; amountCents:number; platformFeeCents:number; businessOrganizationId:string; merchantId:string; }
export interface VerifyStaxQuotePaymentInput { transactionId:string; quoteId:string; quoteVersionId:string; posterId:string; businessOrganizationId:string; merchantId:string; amountCents:number; }
export const StaxQuotePaymentProvider = {
 async charge(input:CreateStaxQuotePaymentInput):Promise<ServiceResult<CreateStaxQuotePaymentResult>> { try { const merchant=await StaxMerchantAccountService.resolveActiveForOrganization(input.businessOrganizationId); if(!merchant)return {success:false,error:{code:'BUSINESS_PAYMENT_ACCOUNT_NOT_READY',message:'The selected Business is not ready to receive Stax payments.'}}; const tx=await chargeStaxPaymentMethod({apiKey:merchant.apiKey,paymentMethodId:input.paymentMethodId,amountCents:input.amountCents,idempotencyId:`quote:${input.quoteId}:${input.quoteVersionId}`,preAuth:false,meta:{quote_id:input.quoteId,quote_version_id:input.quoteVersionId,poster_id:input.posterId,business_organization_id:input.businessOrganizationId,stax_merchant_id:merchant.merchantId}}); if(tx.success!==true||tx.status!=='SUCCESS')return {success:false,error:{code:'PAYMENT_NOT_SUCCEEDED',message:`Stax payment did not succeed (status: ${tx.status??'unknown'}).`}}; return {success:true,data:{transactionId:tx.id,amountCents:input.amountCents,platformFeeCents:input.platformFeeCents,businessOrganizationId:input.businessOrganizationId,merchantId:merchant.merchantId}}; } catch { return {success:false,error:{code:'PAYMENT_CREATION_FAILED',message:'Stax payment could not be created.'}}; } },
 async verifySucceededPayment(input:VerifyStaxQuotePaymentInput):Promise<ServiceResult<void>> { try { const merchant=await StaxMerchantAccountService.resolveActiveForOrganization(input.businessOrganizationId); if(!merchant||merchant.merchantId!==input.merchantId)return {success:false,error:{code:'PAYMENT_MERCHANT_MISMATCH',message:'Stored Stax merchant does not match this payment.'}}; const tx=await getStaxTransaction(input.transactionId,{apiKey:merchant.apiKey}); if(tx.success!==true||tx.status!=='SUCCESS')return {success:false,error:{code:'PAYMENT_NOT_SUCCEEDED',message:`Stax transaction has not succeeded (status: ${tx.status??'unknown'}).`}}; if(tx.currency!=='USD')return {success:false,error:{code:'PAYMENT_CURRENCY_MISMATCH',message:'Stax transaction currency is not USD.'}}; if(Math.round(Number(tx.total)*100)!==input.amountCents)return {success:false,error:{code:'PAYMENT_AMOUNT_MISMATCH',message:'Stax transaction amount does not match quote amount.'}}; const m=tx.meta; if(m?.quote_id!==input.quoteId||m?.quote_version_id!==input.quoteVersionId||m?.poster_id!==input.posterId||m?.business_organization_id!==input.businessOrganizationId||m?.stax_merchant_id!==input.merchantId)return {success:false,error:{code:'PAYMENT_MERCHANT_MISMATCH',message:'Stax transaction merchant binding does not match.'}}; if(tx.is_voided===true)return {success:false,error:{code:'PAYMENT_VOIDED',message:'Stax transaction has been voided.'}}; if(Number(tx.total_refunded??0)>0)return {success:false,error:{code:'PAYMENT_ALREADY_REFUNDED',message:'Stax transaction has already been refunded.'}}; return {success:true,data:undefined}; } catch { return {success:false,error:{code:'PAYMENT_VERIFICATION_FAILED',message:'Stax transaction could not be verified.'}}; } }
};

